### ISSUE TITLE
Broken Map module with Icinga 2.11.4

### ISSUE THREAD

**Issue by marxin** [nbuchwitz/icingaweb2-module-map#115]
Thanks for the great module. However, it does not work with state-of-the-art Icinga:

```
Icinga Web 2 Version | 2.11.4 (11453bfa92a70a44efbf7f966f5e7f27e9300a28)
PHP: 8.1.14
Git commit date: 2023-01-26
```

Map module info (`version | 1.1.0 (2b247ba77125c41c181c0603b95826a4bf74c033)`).

I get the following error when I open `Default map` page:

```
navigation/dashboard?name=maps:11:

Uncaught SyntaxError: Unexpected token '<'
    at b (icinga.min.js:15:866)
    at He (icinga.min.js:15:48373)
    at S.fn.init.append (icinga.min.js:15:49724)
    at S.fn.init.<anonymous> (icinga.min.js:15:50816)
    at $ (icinga.min.js:15:32425)
    at S.fn.init.html (icinga.min.js:15:50494)
    at Icinga.Loader.renderContentToContainer (icinga.min.js:651:588)
    at Icinga.Loader.onResponse (icinga.min.js:615:293)
    at c (icinga.min.js:15:28327)
    at Object.fireWith [as resolveWith] (icinga.min.js:15:29072)
```

**Comment by marxin** [comment]
Surrounding HTML source code:

```
<button id="toggle-sidebar" title="Toggle Menu">
    <i id="close-sidebar" class="icon-angle-double-left"></i>
    <i id="open-sidebar" class="icon-angle-double-right"></i>
</button>
    </div>
    <div id="main" role="main">
        <div id="col1"
            class="container icinga-module module-map"
                    data-icinga-module="map"
                    data-icinga-url="/icingaweb2/map"
                    >
            <script type="text/javascript">
    var map_default_zoom = 4;
var map_default_long = 13.377485;
var map_default_lat = 52.515855;
var map_max_zoom = 19;
var map_max_native_zoom = 19;
var map_min_zoom = 2;
var disable_cluster_at_zoom = 18;
var tile_url = '//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
var cluster_problem_count = 0;
<br />
<b>Deprecated</b>:  preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in <b>/usr/share/icingaweb2/modules/map/application/views/scripts/index/index.phtml</b> on line <b>14</b><br />
var map_show_host = "";
    var service_status = {};
    service_status[0] = ['OK', 'OK'];
    service_status[1] = ['WARNING', 'WARNING'];
    service_status[2] = ['CRITICAL', 'CRITICAL'];
    service_status[3] = ['UNKNOWN', 'UNKNOWN'];
    service_status[99] = ['PENDING', 'PENDING'];
```

**Comment by marxin** [comment]
So it leads to the following PHP 8.1 warning that becomes part of the JS code.
```
preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in <b>/usr/share/icingaweb2/modules/map/application/views/scripts/index/index.phtml
```
