### ISSUE TITLE
Support also geolocation for services

### ISSUE THREAD

**Issue by dgoetz** [nbuchwitz/icingaweb2-module-map#40]
## Expected Behavior
I have an environment with only a small amount of hosts which do many checks representing different regions, so with support for geolocation for services, I would be able to visualize the worldwide state of the provided service.
 
## Current Behavior
With only being able to place hosts on the map, I can only display the location of my sensors, not the service checked.

## Possible Solution
Having the map also display services perhaps with a different icon or having a separate service map to display services which have a geolocation set.

**Comment by nbuchwitz** [comment]
Thanks for the feature request and the additional input on the OSMC hackathon. I'm currently working on a way to save filtered maps (as wanted in #43). Within this feature i'll include services which have a geolocation variable (with a different marker icon). I'll let you know, when i have something to beta test :smile:

**Comment by nbuchwitz** [comment]
Hi Dirk,
as promissed I'm getting back with something to test (still in development):
https://github.com/nbuchwitz/icingaweb2-module-map/tree/feature/fancy-marker-icons

Happy for any suggestions  / feedback

**Comment by nbuchwitz** [comment]
It's possible to filter by objectType (services, hosts or all) by appending objectType=<TYPE> to the url

**Comment by dgoetz** [comment]
Hi, 
sorry it took me a while to have a look into it and also sorry the branch does not seam to work as expected. I have added some geolocation to hosts and services but do not see any icon. When I checkout the master instead it displays the hosts correctly. I already tried to append the filter which does not have affect it. 

What I already would like to suggest is having a service action next to services which has a geolocation defined.

**Comment by nbuchwitz** [comment]
Hi Dirk,

I just committed some pending changes, which also include the service action. The branch was tested with the current standalone vagrant box. 

![screenshot from 2018-02-22 14-39-40](https://user-images.githubusercontent.com/9132055/36541588-b8002934-17de-11e8-87a2-2961253052af.png)

**Comment by dgoetz** [comment]
Hi,
screenshot looks great. But I do not get it work on my system with CentOS7, php7.1 from SCL, icinga2 and icingaweb2 from snapshot (I switched from stable as you mentioned the vagrant box). I started also a vagrant box and there it works. Do I miss any new requirement?
For the filter option it requires objectType=Services (or Hosts), I think singular would be more intuitive so objectType=Service.

**Comment by nbuchwitz** [comment]
Could you try to clone the git repo again and switch to the feature/fancy-marker-icon branch?

```
git clone https://github.com/nbuchwitz/icingaweb2-module-map.git map
cd map
git checkout feature/fancy-marker-icon
```

How does your Service look? I agree about the ``objectType`` values. I'll change it soon.

**Comment by dgoetz** [comment]
Cloning the repo again did not change anything.

The service looks like:
```
# icinga2 object list --type service --name '*!icinga'
Object 'director.localdomain!Icinga' of type 'Service':
  % declared in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_apply.conf', lines 9:1-9:22
  * __name = "director.localdomain!Icinga"
  * action_url = ""
  * check_command = "icinga"
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_templates.conf', lines 17:5-17:28
  * check_interval = 300
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_templates.conf', lines 4:5-4:23
  * check_period = "workhours"
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_templates.conf', lines 3:5-3:30
  * check_timeout = null
  * command_endpoint = ""
  * display_name = "Icinga"
  * enable_active_checks = true
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_templates.conf', lines 7:5-7:31
  * enable_event_handler = true
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_templates.conf', lines 9:5-9:31
  * enable_flapping = false
  * enable_notifications = true
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_templates.conf', lines 6:5-6:31
  * enable_passive_checks = true
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_templates.conf', lines 8:5-8:32
  * enable_perfdata = true
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_templates.conf', lines 10:5-10:26
  * event_command = ""
  * flapping_threshold = 0
  * flapping_threshold_high = 30
  * flapping_threshold_low = 25
  * groups = [ ]
  * host_name = "director.localdomain"
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_apply.conf', lines 9:1-9:22
  * icon_image = ""
  * icon_image_alt = ""
  * max_check_attempts = 3
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_templates.conf', lines 2:5-2:28
  * name = "Icinga"
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_apply.conf', lines 9:1-9:22
  * notes = ""
  * notes_url = ""
  * package = "director"
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_apply.conf', lines 9:1-9:22
  * retry_interval = 60
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_templates.conf', lines 5:5-5:23
  * source_location
    * first_column = 1
    * first_line = 9
    * last_column = 22
    * last_line = 9
    * path = "/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_apply.conf"
  * templates = [ "Icinga", "Icinga", "Generic Service", "host var overrides (Director)" ]
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_apply.conf', lines 9:1-9:22
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_templates.conf', lines 14:1-14:25
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_templates.conf', lines 1:0-1:33
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/001-director-basics.conf', lines 15:1-15:41
  * type = "Service"
  * vars
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/001-director-basics.conf', lines 25:5-25:49
    * geolocation = "49.45989999999999,11.027499999999984"
      % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_templates.conf', lines 18:5-18:61
  * volatile = false
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_templates.conf', lines 11:5-11:20
  * zone = "director.localdomain"
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_apply.conf', lines 9:1-9:22
```

The host looks like:
```
# icinga2 object list --type service --name '*!icinga'
Object 'director.localdomain!Icinga' of type 'Service':
  % declared in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_apply.conf', lines 9:1-9:22
  * __name = "director.localdomain!Icinga"
  * action_url = ""
  * check_command = "icinga"
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_templates.conf', lines 17:5-17:28
  * check_interval = 300
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_templates.conf', lines 4:5-4:23
  * check_period = "workhours"
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_templates.conf', lines 3:5-3:30
  * check_timeout = null
  * command_endpoint = ""
  * display_name = "Icinga"
  * enable_active_checks = true
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_templates.conf', lines 7:5-7:31
  * enable_event_handler = true
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_templates.conf', lines 9:5-9:31
  * enable_flapping = false
  * enable_notifications = true
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_templates.conf', lines 6:5-6:31
  * enable_passive_checks = true
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_templates.conf', lines 8:5-8:32
  * enable_perfdata = true
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_templates.conf', lines 10:5-10:26
  * event_command = ""
  * flapping_threshold = 0
  * flapping_threshold_high = 30
  * flapping_threshold_low = 25
  * groups = [ ]
  * host_name = "director.localdomain"
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_apply.conf', lines 9:1-9:22
  * icon_image = ""
  * icon_image_alt = ""
  * max_check_attempts = 3
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_templates.conf', lines 2:5-2:28
  * name = "Icinga"
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_apply.conf', lines 9:1-9:22
  * notes = ""
  * notes_url = ""
  * package = "director"
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_apply.conf', lines 9:1-9:22
  * retry_interval = 60
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_templates.conf', lines 5:5-5:23
  * source_location
    * first_column = 1
    * first_line = 9
    * last_column = 22
    * last_line = 9
    * path = "/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_apply.conf"
  * templates = [ "Icinga", "Icinga", "Generic Service", "host var overrides (Director)" ]
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_apply.conf', lines 9:1-9:22
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_templates.conf', lines 14:1-14:25
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_templates.conf', lines 1:0-1:33
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/001-director-basics.conf', lines 15:1-15:41
  * type = "Service"
  * vars
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/001-director-basics.conf', lines 25:5-25:49
    * geolocation = "49.45989999999999,11.027499999999984"
      % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_templates.conf', lines 18:5-18:61
  * volatile = false
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_templates.conf', lines 11:5-11:20
  * zone = "director.localdomain"
    % = modified in '/var/lib/icinga2/api/packages/director/director.localdomain-1519308656-0/zones.d/director-global/service_apply.conf', lines 9:1-9:22
```

The action link "Show on map" is shown on host and service (and not on those without geolocation), so I think there is at least the correct custom var. I also tried shorted geolocations taken from the vagrant box.

I tried also different browsers with the same result, so this removes browsers and browser cache from my list.

PHP had some differences on my vm and vagrant box, removing environment variables and configuration options like different memory_limits and timezone it left me with only this PHP module which are on the box in addition.
```
/etc/opt/rh/rh-php71/php.d/20-posix.ini,
/etc/opt/rh/rh-php71/php.d/20-shmop.ini,
/etc/opt/rh/rh-php71/php.d/20-sysvmsg.ini,
/etc/opt/rh/rh-php71/php.d/20-sysvsem.ini,
/etc/opt/rh/rh-php71/php.d/20-sysvshm.ini,
```
So installed them, restarted php-fpm and http, but nothing changed, so I have no idea what could be the difference between the system working and not working and also between the master branch working and the feature branch not working.

**Comment by nbuchwitz** [comment]
Very strange. Do your map markers look like the "old" ones or do they have allready the "new" ones with icons?

**Comment by dgoetz** [comment]
No markers at all (for services and hosts).

I think you found the error because of /map/data/points throws an error:
```
Use of undefined constant ARRAY_FILTER_USE_KEY - assumed 'ARRAY_FILTER_USE_KEY'

#0 /usr/share/icingaweb2/modules/map/application/controllers/DataController.php(155): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer, Array)
#1 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Map\Controllers\DataController->pointsAction()
#2 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#4 /usr/share/php/Icinga/Application/Web.php(409): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#5 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#6 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#7 {main}
```

**Comment by nbuchwitz** [comment]
Strange, ``ARRAY_FILTER_USE_KEY`` should be existing in php versions >= 5.6 

http://php.net/manual/de/array.constants.php

It is possible that your system is somehow using an old php version?  Nevertheless: I should add a check and fallback for older php versions as they are supported by icingaweb2 2.4.

**Comment by Mikesch-mp** [comment]
@dgoetz can you provide a phpinfo() output from your installation. I think your webserver still uses maybe an old php version.
Just create file /usr/share/icingaweb2/public/test.php with this content

```php
<?php
phpinfo();
?>
```

and open it in your browser http://server/icingaweb2/test.php

**Comment by dgoetz** [comment]
I found the problem! After the update to Icinga Web 2 2.5 I started fpm with php-7.1 but http was not configured to use it at all as I had some changes in my webserver configuration.

So now everything works fine. When you merge the feature branch, can you add php >= 5.6 as requirement in the README as I am aware not everyone is happy with Icinga Web 2 using SCL and so perhaps is using a different php version?

**Comment by nbuchwitz** [comment]
I already merged the branch into master. This feature branch will be deleted soon as there will be a release including the new features. As suggested I raised the php dependeny to >= 5.6.

**Comment by nbuchwitz** [comment]
So i guess, i can mark this issue as resolved :smile:
