### ISSUE TITLE
Raise php dependency to >= 5.6

### ISSUE THREAD

**Issue by nbuchwitz** [nbuchwitz/icingaweb2-module-map#53]
As older PHP versions (< 5.6) do not support ``ARRAY_FILTER_USE_KEY``, the data point service breaks with an error message:

```
Use of undefined constant ARRAY_FILTER_USE_KEY - assumed 'ARRAY_FILTER_USE_KEY'

#0 /usr/share/icingaweb2/modules/map/application/controllers/DataController.php(155): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer, Array)
#1 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Map\Controllers\DataController->pointsAction()
#2 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#4 /usr/share/php/Icinga/Application/Web.php(409): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#5 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#6 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#7 {main}
```

**Comment by nbuchwitz** [comment]
Icingaweb2 requirements https://www.icinga.com/docs/icingaweb2/latest/doc/02-Installation/#installation

**Comment by nbuchwitz** [comment]
I raised the php dependency to >= 5.6, which is the same as in icingaweb2.
